name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3 
      - name: Configure builder
        run: docker buildx create --use --driver=docker-container
      - name: Build
        run: docker buildx build --cache-from type=gha --cache-to type=gha,mode=max .
        